version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11

  build:
    commands:
      # Runs our tests and makes our binary
      - mvn package
      - ./publish.sh

cache:
  paths:
    - '/root/.m2/**/*'
