version: "2"

services:
    spigot:
        build:
            context: ""
            dockerfile: spigot-jre-11.Dockerfile
            args:
                JVM_OPTS: "-Xmx2048M -Xms1024M"
                REV: "1.15.2"
        volumes:
            - ./plugins:/minecraft/plugins/
        ports:
            - 25565:25565

        # This lets us use `docker attach server_spigot_1` to send commands to Spigot
        stdin_open: true
        tty: true